[ci] Add global versioning #959 (#1009)
* Update Cargo.toml

* Update release.yaml

* add versions

* fix version

* specify org

* bump version

* remove release test

* Delete build.sh

* Update Cargo.toml

* Create main.rs

* Create Cargo.toml

* Update Cargo.toml

* Update main.rs

* Update package.json

* add agdb_ci

* update release workflow

* add test

* fix test

* add ci workflow

* add readme

* test version validation

* fixes

* revert version

diff --git a/.github/workflows/agdb_ci.yaml b/.github/workflows/agdb_ci.yaml
--- a/.github/workflows/agdb_ci.yaml
+++ b/.github/workflows/agdb_ci.yaml
@@ -1,11 +1,11 @@
-name: agdb_server
+name: agdb_ci
 
 on:
   pull_request:
     branches: ["main"]
 
 env:
-  PROJECT: agdb_server
+  PROJECT: agdb_ci
 
 jobs:
   diff:
@@ -19,9 +19,9 @@ jobs:
       - id: diff
         shell: bash
         run: |
-          if [[ "$(git diff origin/main --name-only -- ${{ env.PROJECT }}/ agdb/src/ agdb/Cargo.toml agdb_derive/src/ agdb_derive/Cargo.toml .github/workflows/${{ env.PROJECT }}.yaml)" != "" ]]; then (echo "diff=true" >> $GITHUB_OUTPUT); fi
+          if [[ "$(git diff origin/main --name-only -- ${{ env.PROJECT }}/ .github/workflows/${{ env.PROJECT }}.yaml Version)" != "" ]]; then (echo "diff=true" >> $GITHUB_OUTPUT); fi
 
-  agdb_server_analyse:
+  agdb_ci_analyse:
     runs-on: ubuntu-latest
     needs: diff
     if: needs.diff.outputs.diff == 'true'
@@ -30,7 +30,7 @@ jobs:
       - uses: actions-rust-lang/setup-rust-toolchain@v1
       - run: cargo clippy --package ${{ env.PROJECT }} --all-targets --all-features -- -D warnings
 
-  agdb_server_coverage:
+  agdb_ci_coverage:
     runs-on: ubuntu-latest
     needs: diff
     if: needs.diff.outputs.diff == 'true'
@@ -39,9 +39,9 @@ jobs:
       - uses: actions-rust-lang/setup-rust-toolchain@v1
       - uses: taiki-e/install-action@cargo-llvm-cov
       - run: rustup component add llvm-tools-preview
-      - run: cargo llvm-cov --package ${{ env.PROJECT }} --all-features --ignore-filename-regex "agdb(.|..)src|agdb_derive|agdb_api|api.rs" --fail-uncovered-functions 0 --fail-uncovered-lines 0 --show-missing-lines
+      - run: cargo llvm-cov --package ${{ env.PROJECT }} --all-features --fail-uncovered-functions 0 --fail-uncovered-lines 0 --show-missing-lines
 
-  agdb_server_format:
+  agdb_ci_format:
     runs-on: ubuntu-latest
     needs: diff
     if: needs.diff.outputs.diff == 'true'
@@ -49,3 +49,14 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions-rust-lang/setup-rust-toolchain@v1
       - run: cargo fmt --package ${{ env.PROJECT }} --check
+
+  validate_version:
+    runs-on: ubuntu-latest
+    needs: diff
+    if: needs.diff.outputs.diff == 'true'
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions-rust-lang/setup-rust-toolchain@v1
+      - run: |
+          cargo run --release --package agdb_ci
+          if [[ "$(git diff --name-only)" != "" ]]; then echo "ERROR: Version changed but some packages have not been updated. Have you forgotten to run agdb_ci?"; exit 1; fi
