consolidate workflows

diff --git a/.github/workflows/agdb_ci.yaml b/.github/workflows/agdb_ci.yaml
--- a/.github/workflows/agdb_ci.yaml
+++ b/.github/workflows/agdb_ci.yaml
@@ -3,48 +3,26 @@ name: agdb_ci
 on:
   pull_request:
     branches: ["main"]
+    paths:
+      - agdb_ci/**
+      - Version
+      - .github/workflows/agdb_ci.yaml
 
 jobs:
-  diff:
+  agdb_ci:
     runs-on: ubuntu-latest
-    outputs:
-      diff: ${{ steps.diff.outputs.diff }}
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - id: diff
-        shell: bash
-        run: |
-          if [[ "$(git diff origin/main --name-only -- agdb_ci/ .github/workflows/agdb_ci.yaml Version)" != "" ]]; then (echo "diff=true" >> $GITHUB_OUTPUT); fi
-
-  agdb_ci_analyse:
-    runs-on: ubuntu-latest
-    needs: diff
-    if: needs.diff.outputs.diff == 'true'
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions-rust-lang/setup-rust-toolchain@v1
-      - run: cargo clippy --package agdb_ci --all-targets --all-features -- -D warnings
-
-  agdb_ci_format:
-    runs-on: ubuntu-latest
-    needs: diff
-    if: needs.diff.outputs.diff == 'true'
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions-rust-lang/setup-rust-toolchain@v1
-      - run: cargo fmt --package agdb_ci --check
-
-  validate_version:
-    runs-on: ubuntu-latest
-    needs: diff
-    if: needs.diff.outputs.diff == 'true'
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - uses: actions-rust-lang/setup-rust-toolchain@v1
+      - run: cargo fmt -p agdb_ci --check
+      - run: cargo clippy -p agdb_ci --all-targets --all-features -- -D warnings
+      - run: cargo run -p agdb_ci -r
       - run: |
-          cargo run --release --package agdb_ci
-          if [[ "$(git diff --name-only)" != "" ]]; then git diff; git diff --name-only; echo "ERROR: Some packages have not been updated. Have you forgotten to run agdb_ci?"; exit 1; fi
+          if [[ "$(git diff --name-only)" != "" ]]; then
+            git diff
+            git diff --name-only
+            echo "ERROR: Some packages have not been updated. Plesae run 'cargo run -p agdb_ci -r' and commit the result."
+            exit 1
+          fi
