add readme

diff --git a/.github/workflows/agdb_ci.yaml b/.github/workflows/agdb_ci.yaml
--- a/.github/workflows/agdb_ci.yaml
+++ b/.github/workflows/agdb_ci.yaml
@@ -19,7 +19,7 @@ jobs:
       - id: diff
         shell: bash
         run: |
-          if [[ "$(git diff origin/main --name-only -- ${{ env.PROJECT }}/ .github/workflows/${{ env.PROJECT }}.yaml)" != "" ]]; then (echo "diff=true" >> $GITHUB_OUTPUT); fi
+          if [[ "$(git diff origin/main --name-only -- ${{ env.PROJECT }}/ .github/workflows/${{ env.PROJECT }}.yaml Version)" != "" ]]; then (echo "diff=true" >> $GITHUB_OUTPUT); fi
 
   agdb_ci_analyse:
     runs-on: ubuntu-latest
@@ -49,3 +49,14 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions-rust-lang/setup-rust-toolchain@v1
       - run: cargo fmt --package ${{ env.PROJECT }} --check
+
+  validate_version:
+    runs-on: ubuntu-latest
+    needs: diff
+    if: needs.diff.outputs.diff == 'true'
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions-rust-lang/setup-rust-toolchain@v1
+      - run: |
+          cargo run --release --package agdb_ci
+          if [[ "$(git diff --name-only)" != "" ]]; then echo "ERROR: Version changed but some packages have not been updated. Have you forgotten to run agdb_ci?"; exit 1; fi
