fixes

diff --git a/.github/workflows/agdb_ci.yaml b/.github/workflows/agdb_ci.yaml
--- a/.github/workflows/agdb_ci.yaml
+++ b/.github/workflows/agdb_ci.yaml
@@ -59,4 +59,4 @@ jobs:
       - uses: actions-rust-lang/setup-rust-toolchain@v1
       - run: |
           cargo run --release --package agdb_ci
-          if [[ "$(git diff --name-only)" != "" ]]; then echo "ERROR: Version changed but some packages have not been updated. Have you forgotten to run agdb_ci?"; exit 1; fi
+          if [[ "$(git diff --name-only)" != "" ]]; then echo "\nERROR: Version changed but some packages have not been updated. Have you forgotten to run agdb_ci?\n"; exit 1; fi
